### PR TITLE
clarify that servers SHOULD send RPL_ENDOFWHOIS

### PR DESCRIPTION
**Pull request by slingamn**
From discussion on https://github.com/Libera-Chat/sable/issues/101

cc @progval

### CODE REVIEW

**Comment by progval** [comment]
@spb pointed out that RPL_ENDOFWHOIS is not sent after ERR_NEEDMOREPARAMS

**Comment by tommyrot** [comment]
> RPL_ENDOFWHOIS is not sent after ERR_NEEDMOREPARAMS

Not after ERR_NONICKNAMEGIVEN either.

**Comment by SadieCat** [comment]
At least in our implementation we only send ERR_ENDOFWHOIS after a well formed WHOIS request. So you'll get it after one ERR_NOSUCHNICK or one or more RPL_WHOIS* numerics. I don't think we need to worry too much about clients sending broken responses imo.

**Comment by slingamn** [comment]
Thanks, I updated this to clarify that the SHOULD only applies when the client's message is well-formed.

**Comment by progval** [comment]
Can/shoud we also make it a MUST when there is no `<target>` (ie. local whois), or should we leave this implementation-specific?

**Comment by slingamn** [comment]
I don't see a compelling reason to change it right now (we would presumably have to do a more detailed investigation of server behaviors, also it's not clear to me that a hard guarantee here would be helpful to clients --- as in the debate over labeled-response, clients should probably implement a timeout regardless?)

I would support opening a follow-up thread to discuss this.

**Comment by slingamn** [comment]
Bump

**Review by progval — APPROVED** [review]

**Review by tommyrot — APPROVED** [review]

**Pull request merged**
