### PR TITLE
Document PRIVMSG server mask

### PR DESCRIPTION
**Pull request by emersion**

### CODE REVIEW

**Comment by emersion** [comment]
cc @progval: does this look good to you?

**Comment by progval** [comment]
Sorry, I just need to test the existing impls first

**Comment by jobe1986** [comment]
Note: there are some iplimentations further restrict the format of the server mask specified, for example I have come accross an implementation where "$*" was not allowed and a format such as "$*.tld" was required instead

**Comment by progval** [comment]
I just checked support with various servers:

Support `$*`/`$$*` and `$*.tld`/`$$*.tld`: Unreal
Support `$*.tld`/$$*.tld` but not `$*`/`$$*` (RPL_NOSUCHNICK): ngircd
Supports only `$$*.tld`: plexus4 (replies with ERR_NOTOPLEVEL if `$$*`, and with NOTICE if `$*.tld`). Additionally, plexus4 requires netadmin status (which is set by services, I believe), not just oper.
Don't support any of them (reply with RPL_NOSUCHNICK): Bahamut, Chary/Solanum, Ergo, irc2, ircu2

So the behavior described in this PR only applies to Unreal. It could be amended to describe Unreal+ngirc+plexus4, but is it worth it?

**Comment by progval** [comment]
Oh also: Unreal and ngircd send messages to all users on the server **but** the sender. I did not check with plexus4 because I'm too lazy to configure services.

**Comment by emersion** [comment]
My main motivation is to add some notes in the spec to tell clients to handle these messages properly, ie. put them in the server buffer if applicable and don't open a new query buffer. Maybe we should only spec the receiving end of this: receiving a message starting with `$` means it's a server-wide broadcast, but leave it unspecified how to send them?

**Comment by progval** [comment]
Sounds good. You could mention in passing what it's for.

> ie. put them in the server buffer if applicable and don't open a new query buffer

Just mention it's a possibility, this should be up to the implementation

**Comment by emersion** [comment]
Done!

**Comment by progval** [comment]
:+1:

**Pull request merged**
