### PR TITLE
Fix the LICENSE header

### PR DESCRIPTION
**Pull request by ProgVal**
So it applies to all original work, not just @DanielOaks'.

Please bikeshed this, then I'll ask the copyright holders to agree to the change.

### CODE REVIEW

**Comment by DanielOaks** [comment]
Yeah this was definitely the intention of the license. Sounds great to me.

**Comment by ProgVal** [comment]
Do you all agree with this license change? It will apply to your existing commits and PRs (and of course, future PRs). Please reply with a comment so we have a written record, no checking the box yourself or using a react.

- [ ] @csmith
- [ ] @DanielOaks
- [ ] @delthas
- [ ] @emersion 
- [ ] @FrozenPigs
- [ ] @hhirtz 
- [ ] @jwheare 
- [ ] @kroppt 
- [ ] @slingamn

(This is a minor change, but let's do this by the book, I don't want to regret it later)

**Comment by DanielOaks** [comment]
I agree with the license change.

**Comment by emersion** [comment]
Ack

**Comment by hhirtz** [comment]
I don't mind my commit being under CC0 1.0 Universal.

**Comment by jwheare** [comment]
Give'er

**Comment by delthas** [comment]
I agree with the license change.

**Comment by delthas** [comment]
I agree with the license change.

**Comment by csmith** [comment]
Yep, happy to licence my tiny contributions under CC0.

**Comment by kroppt** [comment]
I agree with the license change.

**Comment by slingamn** [comment]
I agree with the license change. Thanks for doing this!

**Comment by ProgVal** [comment]
Thanks everyone for the quick answers!

We're only missing @FrozenPigs so I'm merging this now, and we'll just have to wait for their approval to merge #70.

**Pull request merged**
