### PR TITLE
Add a paragraph on handling unexpected parameters of numerics.

### PR DESCRIPTION
**Pull request by progval**

### CODE REVIEW

**Comment by jwheare** [comment]
Never heard of this, seems made up...

**Comment by progval** [comment]
Well yes, I made it up because from what I noticed.

Examples of numerics extended this way: RPL_TIME, RPL_LOCALUSERS, RPL_GLOBALUSERS, RPL_ADMINME, RPL_WHOISACTUALLY
Also, without the human-readable trailing: RPL_TOPICWHOTIME, RPL_BANLIST

**Comment by jwheare** [comment]
I don't think this is a general rule though, "Unless specified otherwise" seems a bit too catch-all, imo this should be specified explicitly on the numerics that do it, because it seems very weird and would likely break a lot of clients.

**Comment by progval** [comment]
This is for future-proofing against servers who will add parameters in the future.
eg. this issue with RPL_WHOISCOUNTRY in kiwiirc: https://github.com/kiwiirc/irc-framework/pull/318/commits/e6c761f9b32a66078c9df326736d4221346b8c3f

**Pull request closed without merging**
