### PR TITLE
Specify ERROR.

### PR DESCRIPTION
**Pull request by progval**
That's all there is to say about it, I believe?

### CODE REVIEW

**Review by emersion — APPROVED** [review]
LGTM!

**Comment by tommyrot** [comment]
ERROR can be used for to report serious or fatal errors, therefore it has overlap with IRCv3's standard replies (ie. `FAIL`). I dislike the use of `MUST` in this context, using `SHOULD` and hinting to IRCv3 is more appropriate IMO.

Also, the following bit is missing (RFC2812 #3.7.4):
> The ERROR message is also used before terminating a client connection.

**Comment by emersion** [comment]
The MUST makes it so ERROR can _only_ be used to report fatal errors. FAIL and friends can be used to report non-fatal errors, so there's no overlap.

RFC 2812 documents ERROR largely in the context of server-to-server communication, which isn't covered in modern docs. The only bit in the RFC about server-to-client communication is the quote you've mentioned. So the MUST above is consistent with the RFC.

**Comment by progval** [comment]
Do you know any server implementation that doesn't close the connection after sending ERROR?

**Comment by DanielOaks** [comment]
I’ve only ever seen ERROR sent to a client right before the connection is
closed, if anyone can pull up examples of other cases I’d be interested to
see them 👀

**Comment by progval** [comment]
FWIW, Supybot/Limnoria checks for the presence of "closing link" in the parameter to know if it should reconnect, so it might have been used for something else. But that code is two decades old, so...

**Pull request merged**
